vich_uploader:
    db_driver: orm

    mappings:
       uploads:
           uri_prefix: /uploads
           upload_destination: '%kernel.project_dir%/public/uploads'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       images:
           uri_prefix: /images
           upload_destination: '%kernel.project_dir%/public/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer